apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: default
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane-providers-sa
          containers:
            - name: package-runtime
              args:
              - --debug
              # env:
              #   - name: GOOGLE_REGION
              #     value: australia-southeast1