apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-bigquery-v2
spec:
  package: docker.io/martinflemingdev/provider-gcp-bigquery-v2.0.0:v1.0.0
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-gcp-config-manager
rules:
  - apiGroups:
      - gcp.upbound.io
    resources:
      - providerconfigs
      - providerconfigusages
    verbs:
      - "*"
