apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-bigquery-v2
spec:
  package: docker.io/martinflemingdev/provider-gcp-bigquery-v2.0.0:v1.0.0
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-gcp-config-manager
rules:
  - apiGroups:
      - gcp.upbound.io
    resources:
      - providerconfigs
      - providerconfigusages
    verbs:
      - "*"
---
# Binding to BQ Pod SA
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-gcp-bigquery-tf-v6-43-0
subjects:
  - kind: ServiceAccount
    name: provider-gcp-bigquery-v2-802be3f262e1    # replace this with BQ service account
    namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-gcp-config-manager