# For BigQuery Data Editor role (project-level)
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: dataform-sa-bigquery-editor
spec:
  forProvider:
    member: serviceAccount:dataform-service-account@axial-life-395119.iam.gserviceaccount.com
    project: "axial-life-395119"
    role: "roles/bigquery.dataEditor"

---
# For BigQuery Job User role (project-level)  
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: dataform-sa-bigquery-job-user
spec:
  forProvider:
    member: serviceAccount:dataform-service-account@axial-life-395119.iam.gserviceaccount.com
    project: "axial-life-395119"
    role: "roles/bigquery.jobUser"