apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}
    # kmsKeyName:
    # labels:
    # messageRetentionDuration:
    # messageStoragePolicy:
    # project:
    # schemaSettings: