apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: stubbed-secretversion.secretmanager.gcp.upbound.io
spec:
  forProvider:  # required
    deletionPolicy: string
    enabled: false
    isSecretDataBase64: false
    secret: string
    secretDataSecretRef:
      key: string
      name: string
      namespace: string
    secretDataWo: string
    secretDataWoVersion: 0.0
    secretRef:
      name: string
      policy:
        resolution: string
        resolve: string
    secretSelector:
      matchControllerRef: false
      matchLabels:
        key: string
      policy:
        resolution: string
        resolve: string
