apiVersion: dataflow.gcp.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This example resource needs an input file stored in a bucket
  labels:
    testing.upbound.io/example-name: big_data_job
  name: big-data-job
spec:
  forProvider:
    name: dataflow-job
    parameters:
      inputFile: gs://cloud-function-test-bucket-1234567890/input.txt
      outputFile: gs://cloud-function-test-bucket-1234567890/output.txt
    region: us-east4
    tempGcsLocation: gs://cloud-function-test-bucket-1234567890/temp/                       # temp dir 
    templateGcsPath: gs://cloud-function-test-bucket-1234567890/dataflow-template_metadata      # template location
    machineType: e2-standard-2
    
    # additionalExperiments: null
    # enableStreamingEngine: null
    # ipConfiguration: null
    # kmsKeyName: null
    # labels: null
    # maxWorkers: null
    # network: null
    # onDelete: null
    # project: null
    # serviceAccountEmail: null
    # skipWaitOnJobTermination: null
    # subnetwork: null
    # transformNameMapping: null
    # zone: null
