apiVersion: dataflow.gcp.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This example resource needs an input file stored in a bucket
  labels:
    testing.upbound.io/example-name: dataflow-job-classic-template
  name: dataflow-job-classic-template
spec:
  forProvider:
    name: dataflow-job-classic-template
    # parameters:                                                                           # Hard coded these params in the template
    #   inputFile: gs://dataflow-classic-template-example/input.txt                         
    #   outputFile: gs://dataflow-classic-template-example/output.txt       
    region: southamerica-west1
    tempGcsLocation: gs://dataflow-classic-template-example/temp/                           # temp dir 
    templateGcsPath: gs://dataflow-classic-template-example/templates/classic-template      # had to be staged via CLI
    machineType: e2-standard-2
    
    # additionalExperiments: null
    # enableStreamingEngine: null
    # ipConfiguration: null
    # kmsKeyName: null
    # labels: null
    # maxWorkers: null
    # network: null
    # onDelete: null
    # project: null
    # serviceAccountEmail: null
    # skipWaitOnJobTermination: null
    # subnetwork: null
    # transformNameMapping: null
    # zone: null
