apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: test-instance
spec:
  forProvider:
    bootDisk:
      - initializeParams:
          - image: debian-cloud/debian-11
    machineType: e2-medium
    networkInterface:
      - network: default
    zone: us-central1-a