apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Dataset
metadata:
  name: exampledataset
  # name: example.dataset   throws Google error
  # name: example-dataset   throws Google error
  # name: example_dataset   throws K8s error    (see issues.yaml)
  labels:
      testing.upbound.io/example-name: exampledataset
spec:
  forProvider:
    access:
      - role: OWNER
        userByEmail: crossplane@axial-life-395119.iam.gserviceaccount.com
      # - role: READER
        # domain: example.domain.com
      # - role: READER
        # specialGroup: projectReaders
    defaultTableExpirationMs: 3600000
    description: This is a test description
    friendlyName: example_dataset
    labels:
      env: default
    location: US
    # project: autofills project ID from providerConfig projectID field
    # defaultCollation: null
    # defaultEncryptionConfiguration: null
    # defaultPartitionExpirationMs: null
    # deleteContentsOnDestroy: null
    # isCaseInsensitive: null
    # maxTimeTravelHours: null