apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Table
metadata:
  name: exampletable
  labels:
      testing.upbound.io/example-name: exampletable
spec:
  forProvider:
    datasetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: exampledataset # using labels to link to dataset
    deletionProtection: false
    labels:
      env: default
    schema: |
      [
        {
          "name": "permalink",
          "type": "STRING",
          "mode": "NULLABLE",
          "description": "The Permalink"
        },
        {
          "name": "state",
          "type": "STRING",
          "mode": "NULLABLE",
          "description": "State where the head office is located"
        }
      ]
    # timePartitioning:
    #   - type: DAY
    # clustering: null
    # datasetId: null
    # datasetIdRef: null
    # description: null
    # encryptionConfiguration: null
    # expirationTime: null
    # externalDataConfiguration: null
    # friendlyName: null
    # materializedView: null
    # project: null
    # rangePartitioning: null
    # view: null
