apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: V2Job
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    launchStage: BETA
    location: us-central1
    template:
      - template:
          - containers:
              - image: us-docker.pkg.dev/cloudrun/container/hello
              
    # binaryAuthorization: null
    # client: null
    # clientVersion: null
    # labels: null
    # project: null
