apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: crossplane-github-private-sandbox
  labels:
    name: crossplane-github-private-sandbox # used in SecretIAMMember
spec:
  forProvider:  # required
    # Minimal secret configuration to create an empty Secret resource in Secret Manager.
    # We do NOT create a SecretVersion here (do that out-of-band via console/gcloud).

    # Project where the secret will be created. Use project ID (recommended).
    project: axial-life-395119

    # Simple automatic replication is the minimal, low-maintenance option.
    # This creates a secret replicated automatically by Google (no additional config).
    replication:
      auto: {}

    # ---------------------- commented unused fields ----------------------
    # The following are valid fields but intentionally omitted in this minimal
    # configuration. They're shown for documentation and to make it clear what
    # you would add if you wanted features like rotation, CMK encryption, etc.

    # annotations:           # Optional free-form metadata annotations
    #   key: string

    # deletionProtection: false  # Prevents deletion of the secret resource when true

    # expireTime: string  # Optional: set an expiration timestamp for the secret

    # labels:               # Optional labels map
    #   key: value

    # Replication using a CMEK (customer-managed KMS key):
    # replication:
    #   userManaged:
    #     replicas:
    #       - location: europe-west1
    #         customerManagedEncryption:
    #           kmsKeyName: projects/axial-life-395119/locations/global/keyRings/mykr/cryptoKeys/mykey

    # rotation:             # Optional rotation configuration (we skip rotation here)
    #   nextRotationTime: "2025-10-01T00:00:00Z"
    #   rotationPeriod: "2592000s"  # example: 30 days in seconds

    # topics:               # Optional Pub/Sub notification topics
    # - name: projects/axial-life-395119/topics/secret-changes

    # ttl: string           # Time-to-live for secret (not commonly used)

    # versionAliases:       # Map friendly aliases to versions
    #   latest: "1"

    # versionDestroyTtl: string  # Optional automatic destruction TTL for versions

    # --------------------------------------------------------------------

    # Notes:
    # - After applying this Crossplane Secret resource, add the secret value via
    #   the console or gcloud to create a SecretVersion. Example:
    #     echo -n "$GITHUB_PAT" | gcloud secrets versions add github-dataform-private-sandbox --data-file=- --project=axial-life-395119
    # - Do NOT commit secret payloads into git. Only the secret resource reference
    #   (the secretId) should be kept in GitOps manifests.
