apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: crossplane-bucket-destroytrue
  # Name of K8s object AND name of GCP Bucket, must be globally unique! 
  # Throws misleading "permissions/bucket does not exist" error if name isn't globally unique
  name: martinflemingdevdestroytrue
spec:
  forProvider:
    forceDestroy: true 
    location: US
    # cors:
    #   - maxAgeSeconds: 3600
    #     method:
    #       - GET
    #       - HEAD
    #       - PUT
    #       - POST
    #       - DELETE
    #     origin:
    #       - http://example.com
    #     responseHeader:
    #       - "*"
    # uniformBucketLevelAccess: false
    # website:
    #   - mainPageSuffix: index.html
    #     notFoundPage: 404.html


    # autoclass: null
    # customPlacementConfig: null
    # defaultEventBasedHold: null
    # encryption: null
    # labels: null
    # lifecycleRule: null
    # logging: null
    # project: null
    # publicAccessPrevention: null
    # requesterPays: null
    # retentionPolicy: null
    # storageClass: null
    # versioning: null
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: crossplane-bucket-destroyfalse
  # Name of K8s object AND name of GCP Bucket, must be globally unique! 
  # Throws misleading "permissions/bucket does not exist" error if name isn't globally unique
  name: martinflemingdevdestroyfalse
spec:
  forProvider:
    forceDestroy: false 
    location: US