apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  labels:
    testing.upbound.io/example-name: wordcount
  name: wordcount
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-bucket
    content: |
      {
        "description": "An example pipeline that counts words in the input file.",
        "name": "Word Count",
        "parameters": [
          {
            "regexes": [
              "^gs:\\/\\/[^\\n\\r]+$"
            ],
            "name": "input",
            "helpText": "Path of the file pattern glob to read from - for example, gs://dataflow-samples/shakespeare/kinglear.txt",
            "label": "Input Cloud Storage file(s)"
          },
          {
            "regexes": [
              "^gs:\\/\\/[^\\n\\r]+$"
            ],
            "name": "output",
            "helpText": "Path and filename prefix for writing output files - for example, gs://MyBucket/counts",
            "label": "Output Cloud Storage file(s)"
          }
        ]
      }
    contentType: application/json
    name: template-metadata-file
    temporaryHold: False