apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  name: exmple-bucketobject
spec:
  forProvider:
    bucket: null
    bucketRef: null
    bucketSelector: null
    cacheControl: null
    content: null
    contentDisposition: null
    contentEncoding: null
    contentLanguage: null
    contentType: null
    customerEncryption: null
    detectMd5Hash: null
    eventBasedHold: null
    kmsKeyName: null
    metadata: null
    name: null
    source: null
    storageClass: null
    temporaryHold: null
