apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    # Note from the upbound marketplace example:
    upjet.upbound.io/manual-intervention: BucketObject does not support source field
    # This would be great to have ... otherwise we're down to text files
  labels:
    testing.upbound.io/example-name: input
  name: input
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-bucket
    #########################################################################################
    # BucketObject does not support source field 
    # https://github.com/upbound/provider-gcp/issues/9
    #########################################################################################
    # contentType: application/zip
    # name: test.zip
    # source: /home/martinfleming/src/crossplane/gcp/crossplane-gcp/resources/Storage/test.zip
    # 
    # when using "source" field, getting this error even though file exists
    # apply failed: open /home/martinfleming/src/crossplane/gcp/crossplane-gcp/resources/Storage/test.zip: 
    # no such file or directory:
    #########################################################################################
    content: "Content of text file goes here"
    contentType: text/plain
    name: input.txt
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  labels:
    testing.upbound.io/example-name: output
  name: output
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-bucket
    content: "Content of text file goes here"
    contentType: text/plain
    name: output.txt
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  labels:
    testing.upbound.io/example-name: temp
  name: temp
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-bucket
    # contentType: Folder   # not needed, but can be included
    name: temp/             # folder name should end with '/'
    content: ' '            # content is ignored but should be non-empty
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  labels:
    testing.upbound.io/example-name: staging
  name: staging
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-bucket

    name: staging/          # folder name should end with '/'
    content: ' '            # content is ignored but should be non-empty
