apiVersion: dataflow.gcp.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This example resource needs an input file stored in a bucket
  labels:
    testing.upbound.io/example-name: dataflow-job-example-word-count
  name: dataflow-job-example-word-count
spec:
  forProvider:
    name: dataflow-job-example-word-count
    parameters:
      inputFile: gs://dataflow-classic-template-example/input.txt
      output: gs://dataflow-classic-template-example/output/
    region: southamerica-west1
    tempGcsLocation: gs://dataflow-classic-template-example/temp/                       # temp dir 
    templateGcsPath: gs://dataflow-templates-southamerica-west1/latest/Word_Count     # template location
    machineType: e2-standard-2
    
    # additionalExperiments: null
    # enableStreamingEngine: null
    # ipConfiguration: null
    # kmsKeyName: null
    # labels: null
    # maxWorkers: null
    # network: null
    # onDelete: null
    # project: null
    # serviceAccountEmail: null
    # skipWaitOnJobTermination: null
    # subnetwork: null
    # transformNameMapping: null
    # zone: null
